//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deantest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dummy
    {
        public int testID { get; set; }
        public string name { get; set; }
        public Nullable<int> x { get; set; }
        public Nullable<int> y { get; set; }
    }
}
